CREATE TABLE SEDE (
  `CODIGO` BIGINT PRIMARY KEY,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `TELEFONO` VARCHAR(12) NOT NULL,
  `CALLE` VARCHAR(50) NOT NULL,
  `NUMERO` BIGINT NOT NULL,
  `COMUNA` VARCHAR(50) NOT NULL,
  `CIUDAD` VARCHAR(50) NOT NULL
);

CREATE TABLE PERSONA (
  `RUT` VARCHAR(50) PRIMARY KEY,
  `PRIMER_NOMBRE` VARCHAR(50) NOT NULL,
  `SEGUNDO_NOMBRE` VARCHAR(50) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(50) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(50) NOT NULL,
  `SEXO` char(1) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `CODIGO_SEDE` BIGINT NOT NULL
);

CREATE TABLE TIPO_COMPROMISO (
  `CODIGO` BIGINT PRIMARY KEY,
  `NOMBRE` VARCHAR(50) NOT NULL
);

CREATE TABLE COMPROMISO (
  `RUT_PERSONA` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `CODIGO_TIPO_COMPROMISO` BIGINT NOT NULL,
  `FECHA_INICIO` DATE NOT NULL,
  `FECHA_FIN` DATE NOT NULL,
  PRIMARY KEY(`RUT_PERSONA`, `NOMBRE`),
  FOREIGN KEY (`RUT_PERSONA`) REFERENCES PERSONA(`RUT`),
  FOREIGN KEY (`CODIGO_TIPO_COMPROMISO`) REFERENCES TIPO_COMPROMISO(`CODIGO`)
);

CREATE TABLE TELEFONO (
  `RUT_PERSONA` VARCHAR(50) NOT NULL,
  `NUMERO` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`RUT_PERSONA`, `NUMERO`),
  FOREIGN KEY (`RUT_PERSONA`) REFERENCES PERSONA(`RUT`)
);

CREATE TABLE DIRECCION (
  `RUT_PERSONA` VARCHAR(50) NOT NULL,
  `CALLE` VARCHAR(50) NOT NULL,
  `NUMERO` BIGINT NOT NULL,
  `COMUNA` VARCHAR(50) NOT NULL,
  `CIUDAD` VARCHAR(50) NOT NULL,
  FOREIGN KEY (`RUT_PERSONA`) REFERENCES PERSONA(`RUT`)
);

CREATE TABLE TIPO_TURNO (
  `CODIGO` BIGINT PRIMARY KEY,
  `NOMBRE` VARCHAR(50) NOT NULL
);

CREATE TABLE TURNO (
  `CODIGO` BIGINT PRIMARY KEY,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `CODIGO_TIPO_TURNO` BIGINT NOT NULL,
  FOREIGN KEY (`CODIGO_TIPO_TURNO`) REFERENCES TIPO_TURNO(`CODIGO`)
);

CREATE TABLE EMPRESA (
  `RUT` VARCHAR(50) PRIMARY KEY,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `RAZON_SOCIAL` VARCHAR(50) NOT NULL
);

CREATE TABLE SEDE_EMPRESA (
  `RUT_EMPRESA` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `TELEFONO` VARCHAR(12) NOT NULL,
  `CALLE` VARCHAR(50) NOT NULL,
  `NUMERO` BIGINT NOT NULL,
  `COMUNA` VARCHAR(50) NOT NULL,
  `CIUDAD` VARCHAR(50) NOT NULL,
  `CODIGO_TURNO` BIGINT NOT NULL,
  PRIMARY KEY (`RUT_EMPRESA`, `NOMBRE`),
  FOREIGN KEY (`RUT_EMPRESA`) REFERENCES EMPRESA(`RUT`),
  FOREIGN KEY (`CODIGO_TURNO`) REFERENCES TURNO(`CODIGO`)
);